### ISSUE TITLE
Shared memory for matrix A: 132 vs. 128

### ISSUE THREAD

**Issue by yaoyaoding** [Yinghan-Li/YHs_Sample#1]
Hi Yinghan, 

Thanks for your very helpful tutorial on the efficient cuda gemm implementation. 

I have a question about the shared memory size for matrix A. Why does it take `132` instead of `128` as the number of rows here [here](https://github.com/Yinghan-Li/YHs_Sample/blob/3e9daccf9aec061b46dc68a6978cf48f2d7fb021/cuda/gemm/sgemm.cu#L237-L238)? 

I have tried updating the code to use 128 instead of 132 as follows and seems that it works fine.

```c++
    __shared__ __align__(16 * 1024) char smem[16 * 1024];
    float *A_smem = reinterpret_cast<float *>(smem);
    float *B_smem = reinterpret_cast<float *>(smem + 8 * 1024);
    // ...
    A_lds_addr ^= 0x1000;
    B_lds_addr ^= 0x1000;
    A_sts_addr ^= 0x1000;
    B_sts_addr ^= 0x1000;
```

Is there any corner case that requires us to use `132`?

**Comment by Yinghan-Li** [comment]
132 instead of 128 to **avoid shared memory bank conflict**

matrix A is row-major, so for the first warp in the code:

```c++
#pragma unroll
for (int i = 0; i < 4; ++i) {
    ldg32_nc(A_ldg_reg[i],
             A_ldg_ptr + i * A_ldg_step,
             (A_ldg_guard & (1u << i)) != 0);
}
```

thread 0\~7 load A_tile[0\~3][0], A_tile[0\~3][1], ..., A_tile[0\~3][7],

thread 8\~15 load A_tile[4\~7][0], A_tile[4\~7][1], ..., A_tile[4\~7][7],

...


and store to shared memory (column-major) by STS.128 (st.shared.v4.b32) instruction, each STS will access 4 banks.

limited by the hardware, for a 4-bank access STS instruction,  the LD/ST unit will divide a warp into 4 groups (8 threads each group), and try to coalesce shared memory access into memory transactions for each group.

for the 128 case, thread 0, 8, 16, 24 access different banks but they are in different groups, thread 0\~7 in the first group access same banks and trigger 8-way bank conflict.

so take 132 instead of 128 make thread 0\~7 STS access different banks and avoid bank conflict in a group.

@yaoyaoding

**Comment by yaoyaoding** [comment]
Got it, thanks for your explanation!


If I understand correctly, the shared memory addresses accessed by a warp are as follows
```
a a+1 a+2 a+3 a+H a+H+1 a+H+2 a+H+3 a+2H+1 ... a+7H a+7H+1 a+7H+2 a+7H+3
------------- --------------------- ...        -------------------------
thread 8g     thread 8g+1           ...        thread 8g+7

where a is the shared memory address of the first thread in the group, g is the group index in the warp 
and H is the number of shared memory rows.

```
As long as we have H % 32 = 4, the group would access 32 consecutive floats in the shared memory with no bank conflict.
